### ISSUE TITLE
Night mode toggle button

### ISSUE THREAD

**Issue by dreadnoughtroboticsvitcc** [dreadnoughtrobotics/dreadnoughtrobotics.github.io#30]
simple night mode toggle button, toggles to dark mode onClicked
dark mode of website for reference
![image](https://user-images.githubusercontent.com/65171863/133993787-93551f53-0425-4442-8d4f-af83a6048920.png)
<br>

![image](https://user-images.githubusercontent.com/65171863/133993877-be780165-802e-4c99-abc6-9f830a8e3445.png)

**Comment by SuhailAhmedVelorum** [comment]
Do we need to use specific colors or should I just sample from the images?

**Comment by SuhailAhmedVelorum** [comment]
Dropped a PR. Let me know what you think.

**Comment by PratikGarai** [comment]
Closed with #44
