### ISSUE TITLE
AUV Timeline distorted

### ISSUE THREAD

**Issue by PratikGarai** [dreadnoughtrobotics/dreadnoughtrobotics.github.io#37]
![image](https://user-images.githubusercontent.com/58355527/139574142-66a00f07-cc96-43f2-9d51-df8382e84eed.png)

**Comment by k4u5h1k** [comment]
To fix this you must adjust the values of x and y in
```css
height: calc(100%-x);
top: y;
```
of `.main-timeline` within `auvtimeline.css`

![image](https://user-images.githubusercontent.com/59250093/139646932-6a5955a2-0709-46b5-a8d9-c41579313367.png)

**Comment by k4u5h1k** [comment]
![image](https://user-images.githubusercontent.com/59250093/139649348-1bcdf3a9-cc96-405c-af1a-c26e2a6bcc1d.png)
`x=31;y=15.7` fixes it

**Comment by PratikGarai** [comment]
Closing for now.
